-- Custodi 451 — tabella proprietari (allowlist + associazione nome→unità)
-- Leggibile solo da utenti loggati. Esegui nel SQL Editor.
create table if not exists public.proprietari (
  unita text primary key, palazzina text, interno text, nome text not null, ruolo text default 'proprietario');
alter table public.proprietari enable row level security;
drop policy if exists proprietari_read on public.proprietari;
create policy proprietari_read on public.proprietari for select to authenticated using (true);
insert into public.proprietari (unita,palazzina,interno,nome) values
('A/01','A','1','Mantini Fabrizio - Losurdo C'),
('A/02','A','2','Cocola Giuseppe'),
('A/03','A','3','Bettini Marco - Ugatti Lucia'),
('A/04','A','4','Nobile Marzia-Lancia Valerio'),
('A/05','A','5','Carresi L. - Silvestri A.'),
('A/06','A','6','Genga V. - Cappellini P.'),
('A/07','A','7','Romani Barbara'),
('A/08','A','8','Troiani Angela'),
('A/09','A','9','Sanna Mauro'),
('A/10','A','10','Schneider Albina - Mainardi F'),
('A/11','A','11','Marinelli Concetta'),
('A/12','A','12','Ricci Patrizia'),
('A/13','A','13','Casini Maria Grazia'),
('A/14','A','14','Basti Roberto'),
('A/15','A','15','De Luca Angela'),
('B/01','B','1','Paletta Laura'),
('B/02','B','2','Pierfrancesco Pierangelini'),
('B/03','B','3','Bongini Claudio - Baronessa'),
('B/04','B','4','Graziani Augusto - Pasquali'),
('B/05','B','5','Viggiani Caterina'),
('B/06','B','6','Cristina Conti Stefano - Masin'),
('B/07','B','7','Coccia Anna'),
('B/08','B','8','Bernava A. - Coccia A.'),
('B/09','B','9','Morizio Andrea - Ferrini Nicol'),
('B/10','B','10','Scocchi Gabriella'),
('B/11','B','11','Raffoni Emanuela'),
('B/12','B','12','Rizzi G. - Diodati M.'),
('C/01','C','1','Luverà Bruno - Luverà Cinzia'),
('C/02','C','2','Vermigli Andrea - Sciarratta B'),
('C/03','C','3','Accardo - Graziani'),
('C/04','C','4','Tagliacozzo Emma'),
('C/05','C','5','Piccioni S. - Bassani C.'),
('C/06','C','6','Bordonali Rita - Naspi Gianfr'),
('C/07','C','7','Di Gasbarro M. Margherita'),
('C/08','C','8','Ridolfi Daniela'),
('C/09','C','9','Giordano Alessandro - Giorda'),
('D/01','D','1','Menditto Biagio'),
('D/02','D','2','Nicolai - Abrami'),
('D/03','D','3','Venturi L. - Boschi A.'),
('D/04','D','4','Totteri Gianluca - Sampoli Ca'),
('D/05','D','5','Motta Maria - Ferraguto Fabio'),
('D/06','D','6','Colarusso Pasquale - Colaru'),
('D/07','D','7','Campodonico Vincenzo - Tuc'),
('D/08','D','8','Pasqualini Guido'),
('D/09','D','9','Boccardi Ennio - Marini Marin'),
('D/10','D','10','Appiani Marisa'),
('D/11','D','11','Ferreri Maria Vittoria'),
('D/12','D','12','Pignataro Pietro Giuseppe'),
('D/13','D','13','D''Agostino Filippo - Vitozzi A'),
('D/14','D','14','Ugolini Fabio - D''Agelosante'),
('E/01','E','1','Cecilia Marco - Dandini Ilaria'),
('E/02','E','2','Nastasi Anna'),
('E/03','E','3','Canipari Paola'),
('E/04','E','4','Pellegrini Graziella'),
('E/05','E','5','Reale Antonino - Lanzafame'),
('E/06','E','6','Russo Giuliano'),
('E/07','E','7','Lombardo Anna Maria'),
('E/08','E','8','De Nichilo Floriana'),
('E/09','E','9','Genovesi Sante - Lisi Annunz'),
('F/01','F','1','Berterame Assunta - Calcagn'),
('F/02','F','2','Mancini Tortora Manuela CP 2'),
('F/03','F','3','Bruschi Adele Elisa - Caratelli'),
('F/04','F','4','Ciaccafava Patrizia'),
('F/05','F','5','Giralico Maria Enrica'),
('F/06','F','6','De Angelis - Dionisi'),
('F/07','F','7','Cristini - Fortunato'),
('F/08','F','8','Castelli Valentina - Castelli S'),
('GA/01','GA','1','Traina Rina Letizia Adele'),
('GA/02','GA','2','Palazzi Anna Rosa'),
('GA/03','GA','3','Serini Diego - Rocchi Daniela'),
('GA/04','GA','4','Giovagnoli Dante'),
('GA/05','GA','5','Algranati Monica'),
('GA/06','GA','6','El Hadidi S. - Marra U.'),
('GA/07','GA','7','Magnani Lilia - Forino Alessa'),
('GA/08','GA','8','Di Nappo Lidia'),
('GB/01','GB','1','Sainato Teresa'),
('GB/02','GB','2','Calabrese Massimo - Dentini'),
('GB/03','GB','3','Pane Maria'),
('GB/04','GB','4','Mottola E. - Oliviero C.'),
('GB/05','GB','5','Marrocco - Serafini'),
('GB/06','GB','6','De Angelis Nicola'),
('GB/07','GB','7','Di Domenica - Vespa'),
('GB/08','GB','8','Piu Carla - Rizzi Salvatore'),
('H/01','H','1','Barbieri Giuseppe'),
('H/02','H','2','Pacifici Massimo'),
('H/03','H','3','Trillò Salvatore'),
('H/04','H','4','Scalabrin Daniela'),
('H/05','H','5','Oppedisano Antonella'),
('H/06','H','6','Ghiraldelli Rita Angela'),
('H/07','H','7','Innocenzi M. - Spinella S.'),
('H/08','H','8','Flamini Martina'),
('H/09','H','9','Restivo Laura'),
('H/10','H','10','Mariasole Lauro'),
('H/11','H','11','Picchiotti G. - Quaglieri'),
('H/12','H','12','Perelli Alessandro'),
('H/13','H','13','Chiarini Donato'),
('H/14','H','14','De Lucia Tiziana - Ghiraldelli'),
('I/01','I','1','Geraci P. - Cinelli V.'),
('I/02','I','2','Cavaliere Amelia - Penzo Ro'),
('I/03','I','3','Barletta Paola'),
('I/04','I','4','Cocci Andrea'),
('I/05','I','5','Carulli Francesco'),
('I/06','I','6','Ventura Antonella'),
('I/07','I','7','Lattanzi Riccardo - Gramigni'),
('I/08','I','8','Lantieri Alessandro - Lantieri'),
('I/09','I','9','Meli Carmela'),
('I/10','I','10','Iannantuoni Matteo - Paiella'),
('I/11','I','11','Ionta Pasquale'),
('I/12','I','12','Pasqualini Franca'),
('I/13','I','13','Lercari Maria Grazia'),
('L/01','L','1','Bergamini - Mazzitelli'),
('L/02','L','2','Ceccarelli Luigi - Vittorini Vitt'),
('L/03','L','3','Orsini A. - Cilia D.'),
('L/04','L','4','Caputo Viviana'),
('L/05','L','5','Caroti Cristina'),
('L/06','L','6','Bella Pasqualino - Olivieri Lor'),
('L/07','L','7','Console Francesco'),
('L/08','L','8','Piu Alessandra'),
('L/09','L','9','Morbidelli Alessandro'),
('M/01','M','1','- Zamagna Stefano - Righini M'),
('M/02','M','2','La Forgia Annunziata'),
('M/03','M','3','Gasparre C. F. - Gasparre A.'),
('M/04','M','4','Francesco Ranauro'),
('M/06','M','6','Oggianu Pietro - Medros Ang'),
('M/07','M','7','Bianchi Massimiliano'),
('M/08','M','8','Esposito Francesco'),
('M/09','M','9','Boscaino G. - Caniglia C.'),
('M/11','M','11','Bastiancich Sergio'),
('M/12','M','12','Seralessandri Claudia'),
('M/13','M','13','Pelorosso Alessandra'),
('M/14','M','14','Campi Massimo'),
('M/15','M','15','Polimeni Mariarosa'),
('M/16','M','16','De Vita Stefano - Rennella C'),
('N/01','N','1','Labia Marco-Gobbi Alessandr'),
('N/02','N','2','Picano Francesco'),
('N/03','N','3','Picano Francesco'),
('N/04','N','4','Torricelli Natale - Colognola A'),
('N/05','N','5','Cerasoli Ivana - Pace Sergio'),
('N/06','N','6','Birtig Maria - Fardin Anna Pa'),
('N/07','N','7','Pane Silvana'),
('N/08','N','8','Pane Silvana'),
('N/09','N','9','Sacchi Antonella'),
('N/10','N','10','Laura Lulli Maria'),
('N/11','N','11','Caliandro Italo Pietro'),
('N/12','N','12','Caliandro Italo Pietro')
on conflict (unita) do nothing;
